"""add completed_at to panel_assignments

Revision ID: 12d6a4d03012
Revises: a8cc11aae89d
Create Date: 2026-01-01 05:39:18.426165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12d6a4d03012'
down_revision: Union[str, None] = 'a8cc11aae89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel_assignments', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('panel_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panel_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('panel_assignments', 'completed_at')
    # ### end Alembic commands ###
