"""add award_type_id to awards

Revision ID: 2ad678f60804
Revises: f026b2e93b53
Create Date: 2026-02-05 09:26:19.940031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad678f60804'
down_revision: Union[str, None] = 'f026b2e93b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_award_types_code'), 'award_types', type_='unique')
    op.create_index(op.f('ix_award_types_code'), 'award_types', ['code'], unique=True)
    op.add_column('awards', sa.Column('award_type_id', sa.UUID(), nullable=True))
    op.add_column('awards', sa.Column('award_type_label', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'awards', 'award_types', ['award_type_id'], ['id'])
    op.drop_column('awards', 'award_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('award_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'awards', type_='foreignkey')
    op.drop_column('awards', 'award_type_label')
    op.drop_column('awards', 'award_type_id')
    op.drop_index(op.f('ix_award_types_code'), table_name='award_types')
    op.create_unique_constraint(op.f('uq_award_types_code'), 'award_types', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
