"""sync_schema_and_wizard

Revision ID: 35d60f185cec
Revises: a08c43a46191
Create Date: 2026-02-24 08:25:47.035130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d60f185cec'
down_revision: Union[str, None] = 'f67b5e1a2b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_config', sa.Column('setup_complete', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_config', 'setup_complete')
    # ### end Alembic commands ###
