"""add panels and panel assignments

Revision ID: 48987bc02596
Revises: beeac422cbc3
Create Date: 2025-12-30 10:48:33.339335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48987bc02596'
down_revision: Union[str, None] = 'beeac422cbc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('panel_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', 'user_id', name='uq_panel_member')
    )
    op.create_table('panel_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('panel_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nomination_id', sa.UUID(), nullable=False),
    sa.Column('panel_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nomination_id'], ['nominations.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomination_id', 'panel_id', name='uq_nomination_panel')
    )
    op.alter_column('form_fields', 'form_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('panel_reviews', sa.Column('panel_assignment_id', sa.UUID(), nullable=False))
    op.add_column('panel_reviews', sa.Column('task_id', sa.UUID(), nullable=False))
    op.add_column('panel_reviews', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('panel_reviews', sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('uq_unique_task_review', 'panel_reviews', ['panel_assignment_id', 'panel_member_id', 'task_id'])
    op.drop_constraint('panel_reviews_nomination_id_fkey', 'panel_reviews', type_='foreignkey')
    op.drop_constraint('panel_reviews_panel_member_id_fkey', 'panel_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'panel_reviews', 'panel_members', ['panel_member_id'], ['id'])
    op.create_foreign_key(None, 'panel_reviews', 'panel_assignments', ['panel_assignment_id'], ['id'])
    op.create_foreign_key(None, 'panel_reviews', 'panel_tasks', ['task_id'], ['id'])
    op.drop_column('panel_reviews', 'updated_at')
    op.drop_column('panel_reviews', 'nomination_id')
    op.drop_column('panel_reviews', 'comments')
    op.drop_column('panel_reviews', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel_reviews', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('panel_reviews', sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('panel_reviews', sa.Column('nomination_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('panel_reviews', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'panel_reviews', type_='foreignkey')
    op.drop_constraint(None, 'panel_reviews', type_='foreignkey')
    op.drop_constraint(None, 'panel_reviews', type_='foreignkey')
    op.create_foreign_key('panel_reviews_panel_member_id_fkey', 'panel_reviews', 'users', ['panel_member_id'], ['id'])
    op.create_foreign_key('panel_reviews_nomination_id_fkey', 'panel_reviews', 'nominations', ['nomination_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_unique_task_review', 'panel_reviews', type_='unique')
    op.drop_column('panel_reviews', 'reviewed_at')
    op.drop_column('panel_reviews', 'comment')
    op.drop_column('panel_reviews', 'task_id')
    op.drop_column('panel_reviews', 'panel_assignment_id')
    op.drop_constraint(None, 'forms', type_='foreignkey')
    op.drop_column('forms', 'cycle_id')
    op.alter_column('form_fields', 'form_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('bulk_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'queued'::character varying"), autoincrement=False, nullable=False),
    sa.Column('total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('processed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('success_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('failure_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('error_file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='bulk_jobs_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='bulk_jobs_pkey')
    )
    op.drop_table('panel_assignments')
    op.drop_table('panel_tasks')
    op.drop_table('panel_members')
    op.drop_table('panels')
    # ### end Alembic commands ###
