"""add criteria_field_id to panel_tasks

Revision ID: a08c43a46191
Revises: f50019f36364
Create Date: 2026-02-19 15:29:24.324492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08c43a46191'
down_revision: Union[str, None] = 'f50019f36364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel_tasks', sa.Column('criteria_field_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panel_tasks', 'criteria_field_id')
    # ### end Alembic commands ###
