"""make_forms_independent

Revision ID: a8cc11aae89d
Revises: 48987bc02596
Create Date: 2025-12-31 02:54:33.958806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8cc11aae89d'
down_revision: Union[str, None] = '48987bc02596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bulk_jobs')
    op.alter_column('form_answers', 'nomination_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('form_fields', 'form_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('uq_nomination_panel'), 'panel_assignments', type_='unique')
    op.add_column('panel_reviews', sa.Column('panel_task_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_unique_task_review'), 'panel_reviews', type_='unique')
    op.create_unique_constraint('uq_unique_task_review', 'panel_reviews', ['panel_assignment_id', 'panel_member_id', 'panel_task_id'])
    op.drop_constraint(op.f('panel_reviews_panel_assignment_id_fkey'), 'panel_reviews', type_='foreignkey')
    op.drop_constraint(op.f('panel_reviews_task_id_fkey'), 'panel_reviews', type_='foreignkey')
    op.drop_constraint(op.f('panel_reviews_panel_member_id_fkey'), 'panel_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'panel_reviews', 'panel_members', ['panel_member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'panel_reviews', 'panel_tasks', ['panel_task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'panel_reviews', 'panel_assignments', ['panel_assignment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('panel_reviews', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel_reviews', sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'panel_reviews', type_='foreignkey')
    op.drop_constraint(None, 'panel_reviews', type_='foreignkey')
    op.drop_constraint(None, 'panel_reviews', type_='foreignkey')
    op.create_foreign_key(op.f('panel_reviews_panel_member_id_fkey'), 'panel_reviews', 'panel_members', ['panel_member_id'], ['id'])
    op.create_foreign_key(op.f('panel_reviews_task_id_fkey'), 'panel_reviews', 'panel_tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('panel_reviews_panel_assignment_id_fkey'), 'panel_reviews', 'panel_assignments', ['panel_assignment_id'], ['id'])
    op.drop_constraint('uq_unique_task_review', 'panel_reviews', type_='unique')
    op.create_unique_constraint(op.f('uq_unique_task_review'), 'panel_reviews', ['panel_assignment_id', 'panel_member_id', 'task_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('panel_reviews', 'panel_task_id')
    op.create_unique_constraint(op.f('uq_nomination_panel'), 'panel_assignments', ['nomination_id', 'panel_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('form_fields', 'form_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('form_answers', 'nomination_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('bulk_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'queued'::character varying"), autoincrement=False, nullable=False),
    sa.Column('total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('processed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('success_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('failure_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('error_file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('bulk_jobs_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bulk_jobs_pkey'))
    )
    # ### end Alembic commands ###
