"""add bulk_jobs table

Revision ID: beeac422cbc3
Revises: d21defef9e50
Create Date: 2025-12-26 15:32:42.445116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beeac422cbc3'
down_revision: Union[str, None] = 'd21defef9e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bulk_jobs",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="queued"),

        sa.Column("total", sa.Integer(), server_default="0"),
        sa.Column("processed", sa.Integer(), server_default="0"),
        sa.Column("success_count", sa.Integer(), server_default="0"),
        sa.Column("failure_count", sa.Integer(), server_default="0"),

        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("error_file", sa.String(), nullable=True),

        sa.Column("created_by", sa.UUID(), sa.ForeignKey("users.id")),

        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bulk_jobs")
    # ### end Alembic commands ###
