"""add category to forms

Revision ID: f50019f36364
Revises: 5aeee2f71fe0
Create Date: 2026-02-19 03:20:32.534761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50019f36364'
down_revision: Union[str, None] = '5aeee2f71fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_answers', sa.Column('attachment', sa.String(length=500), nullable=True))
    op.add_column('form_fields', sa.Column('allow_file_upload', sa.Boolean(), nullable=True))
    op.add_column('forms', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'category')
    op.drop_column('form_fields', 'allow_file_upload')
    op.drop_column('form_answers', 'attachment')
    # ### end Alembic commands ###
